/* =============================================================
   PLC-CORE-MDE — Ladder Decompiler  v1.0
   /js/compiler/ladder_decompiler.js
   =============================================================
   Convierte un IR compilado (desde FBD o Ladder) de vuelta a
   un programa Ladder editable en ladder.html.

   CONTRATO DE DATOS
   ─────────────────
   Entrada (IR envelope):
     {
       format:  'ir',
       program: { nodes: PlcNode[] },
       order:   number[],          // índices topológicos
       memory:  { X,Y,M,T,C,A,R }
     }

   Cada PlcNode del IR tiene:
     id, type, in1, in2, outputs[], preset, value, address:{area,index}

   Salida de decompileIRToLadder:
     Array de rungs en formato paths (compatible con ladder.html):
     [{ id, comment, paths:[[elem,...]], outputs:[coil,...] }]
     elem = { type:'CONTACT', var:'X0', negated:bool }
     coil = { type:'COIL',    var:'Y0', mode:'NORMAL'|'SET'|'RESET' }

   FLUJO INTERNO
   ─────────────
   analyzeIR → detectEdgePatterns → buildExprTree (backward slice)
   → expandXOR → pushDownNOT → distributeAND (SOP, límite 32 términos)
   → flattenSOP → emitRungs (1 término SOP = 1 rung)

   REGLAS CRÍTICAS
   ───────────────
   ❌ NO modifica plc_runtime.cpp ni ningún archivo C++
   ❌ NO altera el formato IR
   ❌ NO rompe FBD existente
   ✅ Si IR no convertible → retorna null con análisis, nunca lanza
   ✅ Compatible con window.LadderProgram si está cargado (opcional)
   =============================================================
*/
(function (root, factory) {
  'use strict';
  if (typeof module !== 'undefined' && module.exports) {
    module.exports = factory();
  } else {
    root.LadderDecompiler = factory();
  }
}(typeof self !== 'undefined' ? self : this, function () {
  'use strict';

  // ============================================================
  // CONSTANTES
  // ============================================================

  var MAX_SOP_TERMS = 32;

  // Nivel de convertibilidad por tipo de nodo IR
  var NODE_LEVEL = {
    // Nivel 1 — directamente representables en Ladder
    input1: 1, input2: 1,
    output1: 1, output2: 1, output3: 1, output4: 1,
    and: 1, or: 1, not: 1,
    r_trig: 1, f_trig: 1,
    ton: 1, tof: 1, tp: 1,
    ctu: 1, ctd: 1,
    sr: 1, rs: 1,
    // Nivel 2 — requieren expansión o aproximación
    xor: 2, cmp: 2, blink: 2,
    // Nivel 3 — no convertibles en esta fase
    analog1: 3, scale: 3, pwm: 3
  };

  var LEVEL3_REASON = {
    analog1: 'Analog input has no boolean Ladder equivalent',
    scale:   'Continuous scale function not representable in discrete Ladder',
    pwm:     'PWM output has no IEC 61131-3 Ladder equivalent'
  };

  var LEVEL2_REASON = {
    xor:   'XOR expanded to OR(AND(A,NOT(B)),AND(NOT(A),B))',
    cmp:   'CMP requires auxiliary M address',
    blink: 'BLINK approximated as cascaded TON+TOF'
  };

  // Nodos que son "outputs" — cada uno genera un rung
  // OUTPUT_TYPES: node types that generate a rung (condition → action).
  // Timers and counters (ton/tof/ctu/ctd) are NOT listed here because in
  // Ladder they appear INSIDE the path (as BLOCK elements), not as output
  // coils. The rung is generated by the output node (output1-4, sr, rs)
  // that is driven by the block's Q output.
  var OUTPUT_TYPES = {
    output1: true, output2: true, output3: true, output4: true,
    sr: true, rs: true
    // ton, tof, tp, ctu, ctd intentionally omitted:
    // they are reconstructed as BLOCK elements inside paths by _treeToElem.
  };

  // Block types that should be rendered as BLOCK elements in paths.
  // Used by _buildExprTree to identify timer/counter IR nodes.
  var BLOCK_IR_TYPES = {
    ton: 'TON', tof: 'TOF', tp: 'TP', ctu: 'CTU', ctd: 'CTD'
  };

  // ============================================================
  // TAREA 1-A: analyzeIR
  // ============================================================

  /**
   * analyzeIR(ir) → { convertible, level, warnings, nodeReport }
   *
   * Clasifica cada nodo del IR.
   * level = máximo nivel encontrado.
   * convertible = false si level === 3 o hay ciclos.
   */
  function analyzeIR(ir) {
    if (!ir || !ir.program || !Array.isArray(ir.program.nodes)) {
      return { convertible: false, level: 3,
               warnings: ['Invalid IR: missing program.nodes'],
               nodeReport: {} };
    }

    var nodes    = ir.program.nodes;
    var warnings = [];
    var nodeReport = {};
    var maxLevel = 1;

    // Clasificar nodos
    nodes.forEach(function (nd) {
      var lvl = NODE_LEVEL[nd.type];
      if (lvl === undefined) {
        lvl = 3;
        warnings.push('Unknown node type "' + nd.type + '" (id=' + nd.id + ')');
      }
      var reason = lvl === 3 ? (LEVEL3_REASON[nd.type] || 'Non-convertible: ' + nd.type)
                 : lvl === 2 ? (LEVEL2_REASON[nd.type] || 'Requires expansion: ' + nd.type)
                 : '';
      nodeReport[nd.id] = { level: lvl, reason: reason, type: nd.type };
      if (lvl > maxLevel) maxLevel = lvl;
      if (lvl === 3) warnings.push('Node ' + nd.id + ' (' + nd.type + '): ' + reason);
      if (lvl === 2) warnings.push('Node ' + nd.id + ' (' + nd.type + '): ' + reason);
    });

    // Detectar ciclos (feedback loops)
    var cycleInfo = _detectCycles(nodes);
    if (cycleInfo.hasCycle) {
      maxLevel = 3;
      warnings.push('Cycle detected in IR graph (ids: ' + cycleInfo.ids.join(',') + ')');
    }

    return {
      convertible: maxLevel < 3,
      level:       maxLevel,
      warnings:    warnings,
      nodeReport:  nodeReport
    };
  }

  function _detectCycles(nodes) {
    var n     = nodes.length;
    var adj   = nodes.map(function () { return []; });
    nodes.forEach(function (nd, i) {
      [nd.in1, nd.in2].forEach(function (src) {
        if (src !== null && src !== undefined && src >= 0 && src < n) adj[src].push(i);
      });
    });
    var WHITE = 0, GRAY = 1, BLACK = 2;
    var color = new Array(n).fill(WHITE);
    var cycleIds = [], found = false;
    function dfs(u) {
      color[u] = GRAY;
      adj[u].forEach(function (v) {
        if (found) return;
        if (color[v] === GRAY) { found = true; cycleIds.push(nodes[u].id, nodes[v].id); }
        else if (color[v] === WHITE) dfs(v);
      });
      color[u] = BLACK;
    }
    for (var i = 0; i < n; i++) { if (!found && color[i] === WHITE) dfs(i); }
    return { hasCycle: found, ids: cycleIds };
  }

  // ============================================================
  // TAREA 1-B: Detección de patrones EDGE
  // ============================================================

  /**
   * _detectEdgePatterns(nodes) → { [andIdx]: {type,signalIdx} }
   *
   * Patrón R_TRIG: AND(X, NOT(sr_prev))  donde sr_prev.in1===X y sr_prev.in2===NOT(X)
   * Patrón F_TRIG: AND(NOT(X), sr_prev)  donde sr_prev.in1===X y sr_prev.in2===NOT(X)
   */
  function _detectEdgePatterns(nodes) {
    var edgeMap = {};

    // NOT map: idx → in1 source
    var notSource = {};
    nodes.forEach(function (nd, i) {
      if (nd.type === 'not' && nd.in1 !== null && nd.in1 >= 0) notSource[i] = nd.in1;
    });

    // SR prev-latch fingerprint: sr.in2 must be NOT(sr.in1)
    var srPrevOf = {}; // srIdx → signalIdx
    nodes.forEach(function (nd, i) {
      if (nd.type !== 'sr' && nd.type !== 'rs') return;
      if (nd.in1 === null || nd.in2 === null) return;
      if (notSource[nd.in2] === nd.in1) srPrevOf[i] = nd.in1;
    });

    nodes.forEach(function (nd, i) {
      if (nd.type !== 'and') return;
      var a = nd.in1, b = nd.in2;
      if (a === null || b === null) return;

      // R_TRIG: AND(X, NOT(srPrev))
      if (notSource[b] !== undefined && srPrevOf[notSource[b]] === a) {
        edgeMap[i] = { type: 'R_TRIG', signalIdx: a }; return;
      }
      // R_TRIG alt: AND(NOT(srPrev), X)
      if (notSource[a] !== undefined && srPrevOf[notSource[a]] === b) {
        edgeMap[i] = { type: 'R_TRIG', signalIdx: b }; return;
      }
      // F_TRIG: AND(NOT(X), srPrev)
      if (notSource[a] !== undefined && srPrevOf[b] === notSource[a]) {
        edgeMap[i] = { type: 'F_TRIG', signalIdx: notSource[a] }; return;
      }
      // F_TRIG alt: AND(srPrev, NOT(X))
      if (notSource[b] !== undefined && srPrevOf[a] === notSource[b]) {
        edgeMap[i] = { type: 'F_TRIG', signalIdx: notSource[b] };
      }
    });

    return edgeMap;
  }

  // ============================================================
  // TAREA 1-C: buildExprTree — backward slice desde un nodo output
  // ============================================================

  /**
   * _buildExprTree(nodeIdx, nodes, edgeMap, memo) → ExprTree
   *
   * ExprTree (árbol interno):
   *   { kind:'contact', addr:'X0', negated:bool }
   *   { kind:'not',     child: ExprTree }
   *   { kind:'and',     children: ExprTree[] }
   *   { kind:'or',      children: ExprTree[] }
   *   { kind:'edge',    edgeType:'R_TRIG'|'F_TRIG', addr:'X0' }
   *   { kind:'block',   blockType:'TON'|..., addr, preset }
   *   { kind:'xor',     left: ExprTree, right: ExprTree }
   *   { kind:'unc',     irType, irId }   ← no convertible
   */
  function _buildExprTree(nodeIdx, nodes, edgeMap, memo) {
    if (memo[nodeIdx] !== undefined) return memo[nodeIdx];
    var nd = nodes[nodeIdx];
    if (!nd) return { kind: 'unc', irType: '?', irId: -1 };

    var result;

    // EDGE pattern check first (antes de AND genérico)
    if (nd.type === 'and' && edgeMap[nodeIdx] !== undefined) {
      var ep  = edgeMap[nodeIdx];
      var sig = nodes[ep.signalIdx];
      result = { kind: 'edge', edgeType: ep.type, addr: _addrStr(sig) };
      memo[nodeIdx] = result; return result;
    }

    switch (nd.type) {
      case 'input1': case 'input2':
        result = { kind: 'contact', addr: _addrStr(nd), negated: false };
        break;

      case 'output1': case 'output2': case 'output3': case 'output4':
        // Al hacer backward slice desde un output, seguimos su driver
        result = (nd.in1 !== null && nd.in1 >= 0)
          ? _buildExprTree(nd.in1, nodes, edgeMap, memo)
          : { kind: 'contact', addr: 'X0', negated: false };
        break;

      case 'not':
        if (nd.in1 !== null && nd.in1 >= 0) {
          result = { kind: 'not', child: _buildExprTree(nd.in1, nodes, edgeMap, memo) };
        } else {
          result = { kind: 'unc', irType: 'not-no-input', irId: nd.id };
        }
        break;

      case 'and': {
        var ch = [];
        if (nd.in1 !== null && nd.in1 >= 0) ch.push(_buildExprTree(nd.in1, nodes, edgeMap, memo));
        if (nd.in2 !== null && nd.in2 >= 0) ch.push(_buildExprTree(nd.in2, nodes, edgeMap, memo));
        result = ch.length === 0 ? { kind: 'unc', irType: 'and-empty', irId: nd.id }
               : ch.length === 1 ? ch[0]
               : { kind: 'and', children: ch };
        break;
      }

      case 'or': {
        var co = [];
        if (nd.in1 !== null && nd.in1 >= 0) co.push(_buildExprTree(nd.in1, nodes, edgeMap, memo));
        if (nd.in2 !== null && nd.in2 >= 0) co.push(_buildExprTree(nd.in2, nodes, edgeMap, memo));
        result = co.length === 0 ? { kind: 'unc', irType: 'or-empty', irId: nd.id }
               : co.length === 1 ? co[0]
               : { kind: 'or', children: co };
        break;
      }

      case 'xor':
        result = {
          kind: 'xor',
          left:  (nd.in1 !== null && nd.in1 >= 0) ? _buildExprTree(nd.in1, nodes, edgeMap, memo) : { kind: 'unc', irType: 'xor-l', irId: nd.id },
          right: (nd.in2 !== null && nd.in2 >= 0) ? _buildExprTree(nd.in2, nodes, edgeMap, memo) : { kind: 'unc', irType: 'xor-r', irId: nd.id }
        };
        break;

      case 'sr': case 'rs':
        result = { kind: 'contact', addr: _addrStr(nd), negated: false };
        break;

      case 'r_trig': result = { kind: 'edge', edgeType: 'R_TRIG', addr: _addrStr(nd) }; break;
      case 'f_trig': result = { kind: 'edge', edgeType: 'F_TRIG', addr: _addrStr(nd) }; break;

      case 'ton': case 'tof': case 'tp': {
        // Build the block element for the timer
        var _blk = { kind: 'block', blockType: nd.type.toUpperCase(), addr: _addrStr(nd), preset: nd.preset || 0 };
        // If the timer has a driving input, prepend it as a CONTACT in series.
        // This produces: [CONTACT(X0), BLOCK(TOF)] instead of just [BLOCK(TOF)].
        result = (nd.in1 !== null && nd.in1 !== undefined && nd.in1 >= 0)
          ? { kind: 'and', children: [ _buildExprTree(nd.in1, nodes, edgeMap, memo), _blk ] }
          : _blk;
        break;
      }

      case 'ctu': case 'ctd': {
        // Same pattern: prepend the enable input (in1) as a CONTACT in series.
        var _cblk = { kind: 'block', blockType: nd.type.toUpperCase(), addr: _addrStr(nd), preset: nd.value || 0 };
        result = (nd.in1 !== null && nd.in1 !== undefined && nd.in1 >= 0)
          ? { kind: 'and', children: [ _buildExprTree(nd.in1, nodes, edgeMap, memo), _cblk ] }
          : _cblk;
        break;
      }

      case 'cmp': case 'blink':
        result = { kind: 'unc', irType: nd.type, irId: nd.id };
        break;

      default:
        result = { kind: 'unc', irType: nd.type, irId: nd.id };
    }

    memo[nodeIdx] = result;
    return result;
  }

  function _addrStr(nd) {
    if (!nd) return 'X0';
    if (nd.address) return nd.address.area + nd.address.index;
    if (nd.type === 'input1') return 'X0';
    if (nd.type === 'input2') return 'X1';
    return 'X0';
  }

  // ============================================================
  // TAREA 1-D: Pipeline SOP
  // ============================================================

  // --- expandXOR ---
  function _expandXOR(t) {
    if (!t) return t;
    if (t.kind === 'xor') {
      var A = _expandXOR(t.left), B = _expandXOR(t.right);
      return { kind: 'or', children: [
        { kind: 'and', children: [A, { kind: 'not', child: B }] },
        { kind: 'and', children: [{ kind: 'not', child: A }, B] }
      ]};
    }
    if (t.kind === 'not') return { kind: 'not', child: _expandXOR(t.child) };
    if (t.kind === 'and') return { kind: 'and', children: t.children.map(_expandXOR) };
    if (t.kind === 'or')  return { kind: 'or',  children: t.children.map(_expandXOR) };
    return t;
  }

  // --- pushDownNOT (De Morgan) ---
  function _pushDownNOT(t) {
    if (!t) return t;
    if (t.kind === 'not') {
      var c = _pushDownNOT(t.child);
      if (c.kind === 'not')  return c.child;
      if (c.kind === 'and')  return { kind: 'or',  children: c.children.map(function(x){ return _pushDownNOT({ kind:'not', child:x }); }) };
      if (c.kind === 'or')   return { kind: 'and', children: c.children.map(function(x){ return _pushDownNOT({ kind:'not', child:x }); }) };
      return { kind: 'not', child: c };
    }
    if (t.kind === 'and') return { kind: 'and', children: t.children.map(_pushDownNOT) };
    if (t.kind === 'or')  return { kind: 'or',  children: t.children.map(_pushDownNOT) };
    return t;
  }

  // --- estimateSopSize ---
  function _estimateSOP(t) {
    if (!t) return 1;
    if (t.kind === 'and') return t.children.reduce(function(a,c){ return a * _estimateSOP(c); }, 1);
    if (t.kind === 'or')  return t.children.reduce(function(a,c){ return a + _estimateSOP(c); }, 0);
    return 1;
  }

  // --- distributeAND (SOP) con límite MAX_SOP_TERMS ---
  function _distributeAND(t, state) {
    if (!t || state.overflowed) return t;
    if (t.kind === 'or')  return { kind: 'or',  children: t.children.map(function(c){ return _distributeAND(c, state); }) };
    if (t.kind !== 'and') return t;

    // Procesar hijos recursivamente
    var processed = t.children.map(function(c){ return _distributeAND(c, state); });
    if (state.overflowed) return { kind: 'and', children: processed };

    var orKids  = processed.filter(function(c){ return c.kind === 'or'; });
    var flatKids = processed.filter(function(c){ return c.kind !== 'or'; });

    if (orKids.length === 0) return { kind: 'and', children: processed };

    // Estimar antes de expandir
    if (_estimateSOP({ kind: 'and', children: processed }) > MAX_SOP_TERMS) {
      state.overflowed = true;
      return { kind: 'and', children: processed };
    }

    // Producto cartesiano
    var base = flatKids.length > 0 ? [{ kind: 'and', children: flatKids }] : [{ kind: 'and', children: [{ kind: 'contact', addr: '_TRUE_', negated: false }] }];
    var result = orKids.reduce(function(acc, orNode) {
      var expanded = [];
      acc.forEach(function(accTerm) {
        orNode.children.forEach(function(orChild) {
          var aKids = accTerm.kind === 'and' ? accTerm.children : [accTerm];
          var bKids = orChild.kind === 'and'  ? orChild.children  : [orChild];
          var merged = aKids.concat(bKids).filter(function(x){ return !(x.kind === 'contact' && x.addr === '_TRUE_'); });
          expanded.push(merged.length === 1 ? merged[0] : { kind: 'and', children: merged });
        });
      });
      return expanded;
    }, base);

    return result.length === 1 ? result[0] : { kind: 'or', children: result };
  }

  // --- flattenSOP ---
  function _hashTree(t) {
    if (!t) return '?';
    if (t.kind === 'contact') return 'C:' + t.addr + ':' + (t.negated ? '1' : '0');
    if (t.kind === 'edge')    return 'E:' + t.edgeType + ':' + t.addr;
    if (t.kind === 'not')     return 'NOT(' + _hashTree(t.child) + ')';
    if (t.kind === 'block')   return 'BLK:' + t.blockType + ':' + t.addr;
    if (t.kind === 'and')     return 'AND(' + t.children.map(_hashTree).sort().join(',') + ')';
    if (t.kind === 'or')      return 'OR('  + t.children.map(_hashTree).sort().join(',') + ')';
    return t.kind + ':?';
  }

  function _dedupeByHash(items) {
    var seen = {}, out = [];
    items.forEach(function(x){ var h = _hashTree(x); if (!seen[h]) { seen[h] = true; out.push(x); } });
    return out;
  }

  function _flattenSOP(t) {
    if (!t) return t;
    if (t.kind === 'or') {
      var flat = [];
      t.children.map(_flattenSOP).forEach(function(c){ if (c.kind === 'or') c.children.forEach(function(x){ flat.push(x); }); else flat.push(c); });
      flat = _dedupeByHash(flat);
      return flat.length === 1 ? flat[0] : { kind: 'or', children: flat };
    }
    if (t.kind === 'and') {
      var fand = [];
      t.children.map(_flattenSOP).forEach(function(c){ if (c.kind === 'and') c.children.forEach(function(x){ fand.push(x); }); else fand.push(c); });
      fand = _dedupeByHash(fand);
      return fand.length === 1 ? fand[0] : { kind: 'and', children: fand };
    }
    if (t.kind === 'not') return { kind: 'not', child: _flattenSOP(t.child) };
    return t;
  }

  // ============================================================
  // TAREA 1-E: Conversión ExprTree → paths format (ladder.html)
  // ============================================================

  /**
   * _treeToPathsElem(tree) → elem | null
   * Convierte un nodo hoja de ExprTree a un elemento paths format.
   * Solo hojas: contact, not(contact), edge → CONTACT.
   */
  function _treeToElem(t) {
    if (!t) return null;
    if (t.kind === 'contact') return { type: 'CONTACT', var: t.addr, negated: t.negated };
    if (t.kind === 'not' && t.child && t.child.kind === 'contact') return { type: 'CONTACT', var: t.child.addr, negated: true };
    if (t.kind === 'not' && t.child) return { type: 'CONTACT', var: _addrFromTree(t.child), negated: true };
    if (t.kind === 'edge')   return { type: 'CONTACT', var: t.addr, negated: false };
    if (t.kind === 'block') {
      // Reconstruct a proper BLOCK element — NOT a contact.
      // The Ladder editor and compileLadder both expect this format.
      return { type: 'BLOCK', blockType: t.blockType, id: t.addr, preset: t.preset || 0 };
    }
    if (t.kind === 'and') {
      // AND en un "leaf" inesperado — tomar primer hijo
      var first = t.children && t.children[0] ? _treeToElem(t.children[0]) : null;
      return first;
    }
    return null;
  }

  function _addrFromTree(t) {
    if (!t) return 'X0';
    if (t.kind === 'contact' || t.kind === 'edge' || t.kind === 'block') return t.addr;
    if (t.kind === 'not') return _addrFromTree(t.child);
    return 'X0';
  }

  /**
   * _sopTermToPath(term) → [elem, ...] (una path row = serie en AND)
   * term puede ser: un AND (varios elems en serie) o un leaf (un elem).
   */
  function _sopTermToPath(term) {
    if (!term) return [];
    if (term.kind === 'and') {
      var elems = [];
      term.children.forEach(function(c) {
        var e = _treeToElem(c);
        if (e) elems.push(e);
      });
      return elems;
    }
    var e = _treeToElem(term);
    return e ? [e] : [];
  }

  /**
   * _extractSopTerms(tree) → [term, ...]
   * Si es OR → sus hijos. Si es otra cosa → [tree].
   */
  function _extractSopTerms(tree) {
    if (!tree) return [];
    if (tree.kind === 'or') return tree.children;
    return [tree];
  }

  // ============================================================
  // TAREA 1-F: Topológico (fallback si ir.order falta)
  // ============================================================

  function _computeOrder(nodes) {
    var n    = nodes.length;
    var indeg = new Array(n).fill(0);
    var adj  = nodes.map(function(){ return []; });
    nodes.forEach(function(nd, j) {
      [nd.in1, nd.in2].forEach(function(src) {
        if (src !== null && src !== undefined && src >= 0 && src < n) { adj[src].push(j); indeg[j]++; }
      });
    });
    var q = [], res = [];
    indeg.forEach(function(d, i){ if (d === 0) q.push(i); });
    while (q.length) { var cur = q.shift(); res.push(cur); adj[cur].forEach(function(nx){ if (--indeg[nx] === 0) q.push(nx); }); }
    for (var i = 0; i < n; i++) if (res.indexOf(i) < 0) res.push(i);
    return res;
  }

  // ============================================================
  // TAREA 1-G: irToLadderAST — reconstruye rungs desde IR
  // ============================================================

  /**
   * irToLadderAST(ir) → rungs[] en formato paths, o null si no convertible.
   *
   * Retorna array de rungs compatible con ladder.html:
   *   [{ id, comment, paths:[[elem,...]], outputs:[coil,...] }]
   */
  function irToLadderAST(ir) {
    var analysis = analyzeIR(ir);
    if (!analysis.convertible) return null;

    var nodes   = ir.program.nodes;
    var order   = (ir.order && ir.order.length > 0) ? ir.order : _computeOrder(nodes);
    var edgeMap = _detectEdgePatterns(nodes);

    // Identificar SR latches que son prev-latch de EDGE (no emitir como rung propio)
    var edgeLatchSet = {};
    Object.keys(edgeMap).forEach(function(andIdx) {
      var ep = edgeMap[andIdx];
      nodes.forEach(function(nd, i) {
        if ((nd.type === 'sr' || nd.type === 'rs') && nd.in1 === ep.signalIdx) edgeLatchSet[i] = true;
      });
    });

    var rungs     = [];
    var rungCount = 0;

    order.forEach(function(nodeIdx) {
      var nd = nodes[nodeIdx];
      if (!nd || !OUTPUT_TYPES[nd.type]) return;
      if (edgeLatchSet[nodeIdx]) return;

      var addr       = nd.address || _inferAddr(nd, nodeIdx);
      var outputAddr = addr.area + addr.index;
      var condSrcIdx = nd.in1;

      if (condSrcIdx === null || condSrcIdx === undefined || condSrcIdx < 0) return;

      // Backward slice → ExprTree
      var memo    = {};
      var rawTree = _buildExprTree(condSrcIdx, nodes, edgeMap, memo);

      // Pipeline SOP
      var t1 = _expandXOR(rawTree);
      var t2 = _pushDownNOT(t1);
      var distState = { overflowed: false };
      var t3 = _distributeAND(t2, distState);
      if (distState.overflowed) return; // SOP explosion — omitir rung
      var t4 = _flattenSOP(t3);

      // Extraer términos SOP → paths
      var terms = _extractSopTerms(t4);
      if (terms.length === 0) return;

      // Determinar modo de acción
      var mode = _actionMode(nd);

      // Política: 1 término SOP = 1 rung
      terms.forEach(function(term, ti) {
        var path = _sopTermToPath(term);
        if (path.length === 0) {
          // Fallback: si el término no produjo elementos, usar un contacto genérico
          path = [{ type: 'CONTACT', var: outputAddr.charAt(0) === 'Y' ? 'X0' : 'X0', negated: false }];
        }

        var coil = { type: 'COIL', var: outputAddr, mode: mode };
        rungs.push({
          id:      'dc_' + rungCount + '_' + ti,
          comment: 'Decompiled from ' + nd.type + ' @ ' + outputAddr,
          paths:   [path],
          outputs: [coil]
        });
      });

      rungCount++;
    });

    return rungs.length > 0 ? rungs : null;
  }

  function _inferAddr(nd, nodeIdx) {
    var map = {
      output1:{ area:'Y', index:0 }, output2:{ area:'Y', index:1 },
      output3:{ area:'Y', index:2 }, output4:{ area:'Y', index:3 },
      input1: { area:'X', index:0 }, input2: { area:'X', index:1 },
      sr:     { area:'M', index:nodeIdx }, rs: { area:'M', index:nodeIdx },
      ton:    { area:'T', index:nodeIdx }, tof:{ area:'T', index:nodeIdx },
      tp:     { area:'T', index:nodeIdx },
      ctu:    { area:'C', index:nodeIdx }, ctd:{ area:'C', index:nodeIdx }
    };
    return map[nd.type] || { area:'M', index:nodeIdx };
  }

  function _actionMode(nd) {
    if (nd.type === 'sr') return 'SET';
    if (nd.type === 'rs') return 'RESET';
    return 'NORMAL';
  }

  // ============================================================
  // TAREA 1-H: decompileIRToLadder — punto de entrada principal
  // ============================================================

  /**
   * decompileIRToLadder(ir) → { rungs, analysis } | null
   *
   * Si convertible → { rungs: [...], analysis }
   * Si no          → null  (con analysis disponible vía analyzeIR)
   *
   * Los rungs son directamente usables en el editor de ladder.html.
   */
  function decompileIRToLadder(ir) {
    var analysis = analyzeIR(ir);

    if (!analysis.convertible) {
      console.warn('[LadderDecompiler] IR not convertible (level 3):', analysis.warnings);
      return null;
    }

    var rungs = irToLadderAST(ir);

    if (!rungs || rungs.length === 0) {
      console.warn('[LadderDecompiler] No rungs generated from IR');
      return null;
    }

    if (analysis.level === 2) {
      console.info('[LadderDecompiler] Level 2 decompilation (some approximations):', analysis.warnings);
    }

    return { rungs: rungs, analysis: analysis };
  }

  // ============================================================
  // MINI EVALUADOR BOOLEANO (para tests de equivalencia)
  // ============================================================

  /**
   * evalIR(ir, inputs) → { 'Y0': bool, ... }
   * inputs: { 'X0': true, 'X1': false, ... }
   * Evalúa solo nodos combinacionales (AND/OR/NOT/input/output).
   * Múltiples outputs con la misma dirección → OR lógico.
   */
  function evalIR(ir, inputs) {
    var nodes = ir.program.nodes;
    var order = (ir.order && ir.order.length > 0) ? ir.order : _computeOrder(nodes);
    var state = new Array(nodes.length).fill(false);

    order.forEach(function(i) {
      var nd = nodes[i];
      if (!nd) return;
      var v1 = (nd.in1 !== null && nd.in1 >= 0) ? state[nd.in1] : false;
      var v2 = (nd.in2 !== null && nd.in2 >= 0) ? state[nd.in2] : false;
      switch (nd.type) {
        case 'input1': case 'input2':
          state[i] = inputs[_addrStr(nd)] === true; break;
        case 'not':   state[i] = !v1; break;
        case 'and':   state[i] = v1 && v2; break;
        case 'or':    state[i] = v1 || v2; break;
        case 'xor':   state[i] = v1 !== v2; break;
        case 'output1': case 'output2': case 'output3': case 'output4':
          state[i] = v1; break;
        default: state[i] = false;
      }
    });

    var out = {};
    nodes.forEach(function(nd, i) {
      if (/^output[1-4]$/.test(nd.type) && nd.address) {
        var k = nd.address.area + nd.address.index;
        out[k] = (out[k] || false) || state[i]; // OR lógico si hay múltiples rungs
      }
    });
    return out;
  }

  // ============================================================
  // PUBLIC API
  // ============================================================

  return {
    // API principal
    analyzeIR:           analyzeIR,
    irToLadderAST:       irToLadderAST,
    decompileIRToLadder: decompileIRToLadder,

    // Sub-funciones del pipeline (debugging/testing)
    detectEdgePatterns:  _detectEdgePatterns,
    expandXOR:           _expandXOR,
    pushDownNOT:         _pushDownNOT,
    distributeAND:       function(t){ var s={overflowed:false}; return _distributeAND(t,s); },
    flattenSOP:          _flattenSOP,
    evalIR:              evalIR,

    // Constantes
    MAX_SOP_TERMS: MAX_SOP_TERMS,
    NODE_LEVEL:    NODE_LEVEL
  };

}));
